### ISSUE TITLE
样式: CSS: Functions

### ISSUE THREAD

**Issue by xvno** [xvno/blog#20]

**Comment by xvno** [comment]
## 函数列表

| Function | Description |
| -- | -- |
| rgba() | Defines colors using the Red-Green-Blue-Alpha model (RGBA) |
| rgb() | Defines colors using the Red-Green-Blue model (RGB) |
| attr() | Returns the value of an attribute of the selected element |
| calc() | Allows you to perform calculations to determine CSS property values |
| cubic-bezier() | Defines a Cubic Bezier curve |
| linear-gradient() | Sets a linear gradient as the background image. Define at least two colors (default: top to bottom) |
| radial-gradient() | Sets a radial gradient as the background image. Define at least two colors (center to edges) |
| hsl() | Defines colors using the Hue-Saturation-Lightness model (HSL) |
| hsla() | Defines colors using the Hue-Saturation-Lightness-Alpha model (HSLA) |


| Rarely Used | ... |
| -- | -- |
| var() | Inserts the value of a custom property |
| repeating-linear-gradient() | Repeats a linear gradient |
| repeating-radial-gradient() | Repeats a radial gradient |


## 样例
### rgba 定义带opacity的rgb颜色
`rgba(red, green, blue, alpha)`
```css
#p1 {background-color:rgba(255,0,0,0.3);} /* red with opacity*/
```
```html
<p id="p1">Red</p>
```
![image](https://user-images.githubusercontent.com/45987576/55904266-0714bb80-5c02-11e9-9712-10a649681779.png)


### attr() 获取本元素的某个属性

```css
a:after {
  content: " (" attr(href) ")";
}
```
```html
<a href="http://vno.io">VNO's</a>
```
![image](https://user-images.githubusercontent.com/45987576/55902760-ca939080-5bfe-11e9-95dc-0ddacc228677.png)

### calc() 

```css
width: calc(100% - 100px);
```

### cubic-bezier

```css
div {
  width: 100px;
  height: 100px;
  background: red;
  transition: width 2s;
  transition-timing-function: cubic-bezier(0.1, 0.7, 1.0, 0.1);
}

div:hover {
  width:300px;
}
```
```html
<div></div>
```
### linear-gradient(direction, color-stop1, color-stop2, ...)
`background-image: linear-gradient(direction, color-stop1, color-stop2, ...);`

```css
div {
 height: 50px;
}
#grad1 {
  background-image: linear-gradient(red, yellow, blue);
}
#grad2 {
  background-image: linear-gradient( 45deg, red, yellow, blue);
}
```
```html
<div id="grad1"></div>
<div id="grad2"></div>
```
![image](https://user-images.githubusercontent.com/45987576/55903582-91f4b680-5c00-11e9-82b5-8e79ab6c59df.png)

### radial-gradient(shape size at position, start-color, ..., last-color);
`background-image: radial-gradient(shape size at position, start-color, ..., last-color);`
参数
- shape: 默认为`ellipsis`, 另一个值为`circle`
- size: farthest-corner (default) closest-side closest-corner farthest-side
- position: 

```html
<div id="grad1"></div>
```
![image](https://user-images.githubusercontent.com/45987576/55903728-e730c800-5c00-11e9-97cc-7d11238d7afd.png)
```css
#grad1 {
  height: 150px;
  width: 200px;
  background-image: radial-gradient(circle, red, yellow, green);
}
```



###  var() 
```css
:root {
  --main-bg-color: coral;  
}

#div1 {
  background-color: var(--main-bg-color);
}
```
