### ISSUE TITLE
样式: CSS: 清除浮动

### ISSUE THREAD

**Issue by xvno** [xvno/blog#35]

**Comment by xvno** [comment]
### 一般清除浮动的目的在于撑开父元素, 以至于不会因为尺寸问题而影响后续元素的布局. 
目前发现两大方向:
1. 在浮动元素后面添加带clear属性的元素/伪类
2. 利用BFC创造"结界"

第 1 类最简单而且目的性很单一, 而第 2 类是我在开发过程中最常用到的.

#### 假定元素组合如下

```html
  <div class="row">
    <p>[[清除浮动的方式]]</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
```
```css
.row {
  .box {
    display: inline-block;
    min-width: 80px;
    min-height: 80px;
    float: left;
  }
}
```
#### BFC结界
> BFC: Block Formatting Context, 一种描述很复杂, 形式却很简单的元素状态
> 一句话描述: 成为BFC状态的元素(Element), 无论其内部元素如何, 都不会影响到外部元素的一种类似沙盒的状态.

怎么触发元素成为BFC状态?
1. position取absolute, fixed
2. float 取left, right
3. display: inline-block...(table类的暂时不考虑)
4. overflow: auto, hidden, scroll
5. <html></html> 这个就不用说了

所以, 只要给父元素 **.row** 添加上面任意的css属性, 把它触发成为BFC状态, 即可清除浮动(包裹浮动), 源码见最后


#### 元素/伪类法
1. 元素法, 即在浮动元素后面添加一个白痴元素, 设置属性clear属性
同时得保证白痴元素为块级元素或显示设置 **display: block;**


```html
<div class="row clearfix">
    <p>白痴</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
    <p></p>
    <!-- <span></span> -->
  </div>
```
```css
.clearfix {
    & > p {
      clear: both;
    }
    // & > span {
    //   clear: both;
    //   display: block;
    // }
}
```
2. 伪类法, 即在父容器后添加 **:after** 伪类, 通过它来清除浮动
同样, 得保证伪类为块级元素
```css
.row:after {
      display: block;
      content: "";
      clear: both;
}
```

**Comment by xvno** [comment]
### 全部代码

```html
<div class="container">
  <div class="row bfc-display">
    <p>bfc: display:inlineblock</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
  <div class="row bfc-position bfc-absolute">
    <p>BFC position:absolute</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
  <div class="row bfc-position bfc-fixed">
    <p>BFC position:fixed</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
  <div class="row bfc-overflow auto">
    <p>bfc: overflow:auto</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
  
  <div class="row bfc-overflow hidden">
    <p>bfc: overflow:hidden</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
  
  <div class="row bfc-overflow scroll">
    <p>bfc: overflow:scroll</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
  
  <div class="row br-clearfix">
    <p>br clearfix</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
    <br>
  </div>

  <div class="row containerclearfix">
    <p>container clearfix</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>

  <div class="row lastchildclearfix">
    <p>last-child clearfix</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>
  
  <div class="row bfc-float">
    <p>bfc: float</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
  </div>

  <div class="row clearfix">
    <p>白痴</p>
    <div class="box">1</div>
    <div class="box">2</div>
    <div class="box">3</div>
    <div class="box">4</div>
    <div class="box">5</div>
<!--     <span></span> -->
    <p></p>
  </div>
</div>
```

```css
.container {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  background-color: #998397;
  .row {
    background-color: #1d1e21;
    color: #ce7834;
    padding: 10px;
    margin-bottom: 10px;
    .box {
      box-sizing: border-box;
      display: inline-block;
      float: left;
      min-width: 80px;
      min-height: 80px;
      margin-right: 10px;
      padding: 5px;
      background-color: #4ecd77;
      &:last-child {
        margin-right: 0;
      }
    }
  }
  .bfc-display {
    display: inline-block;
    width: 100%;
  }
  .bfc-position {
    background-color: white;
  }
  .bfc-absolute {
    position: absolute;
    top: 50px;
    right: 0;
  }

  .bfc-fixed {
    position: fixed;
    top: 240px;
    right: 0;
  }
  .bfc-overflow {
    &.auto {
      overflow: auto;
    }
    &.hidden{
      overflow: hidden;
    }
    &.scroll {
      overflow: scroll;
    }
  }
  
  .bfc-float {
    float: right;
    background-color: white;
    margin-top: -370px;
  }

  .lastchildclearfix {
    display: none;
    color: red;
    .box:last-child {
      width: 100%;
      height: 1px;
      visibility: hidden;
      clear: both;
    }
    transform: translate(0, -100px);
  }

  .br-clearfix {
    br{
      clear: both;
    }
  }
  
  .containerclearfix {
    &:after {
      display: block;
      clear: both;
      content: "";
      background-color: red;
    }
  }
  .clearfix {
    // & > span {
    //   clear: both;
    //   display: block;
    // }
    & > p {
      clear: both;
    }
  }
}
```
