### ISSUE TITLE
约定: Git: 工作流约定

### ISSUE THREAD

**Issue by xvno** [xvno/blog#48]

**Comment by xvno** [comment]
## 粒度划分
### 细粒度
以"完成"以下任意一项

1. 某一项功能 或 代码段
2. 添加必要文件/更改目录结构 + 更新必要配置
3. 修改**所有**需要改正的字段/话述

### 独立

1. 每个提交不应该包含跟它的comment无关的变更, 即描述要覆盖所有变更(细粒度的变更更容易描述, 但<细粒度.3>要满足)
2. 不依赖"第三方分支": merge/rebase操作, 不应对除master, release, dev(develop), raw 之外的第三方分支使用. 项目成员分支间的依赖不应该存在, 即在合并到raw(develop)上之前是不能相互merge/rebase的

## commit/comment

`[<jira-id>: ]<动作类型>: [<模块/文件/功能等逗号分隔>:]+ <简要说明>`

动作类型: Add, Rmv, Mdf, Dbg, Opt
模块/文件/功能
简要说明

```yaml
# 实例
# ": "是英文标点加空格
# 尽量使用原有的词汇, 不要直接翻译成中文

Add: login: logo文件
Mdf: login: footer 配色 和 文案
Rmv: user: 无用的大尺寸图片
SHARP-1008: Dbg: login, user: style: sass文件除虫
SHARP-1009: Opt: profile: 
```
