### ISSUE TITLE
前端: CSS: 常见布局

### ISSUE THREAD

**Issue by xvno** [xvno/blog#59]
## 经典布局

- 两栏布局
- 三栏布局
- 圣杯布局
- 双飞翼布局
- 水平/垂直居中布局

**Comment by xvno** [comment]
### 两栏布局
左右两栏, 左边固定宽度, 右边自适应

```html
<div class="dual-col">
    <div class="left">LEFT</div>
    <div class="right">RIGHT</div>
</div>
```


#### 使用flex
```less
.dual-col-flex {
    display: flex;
    .left {
        flex: 0 0 200px;
    }
    .left {
        //  flex: auto;
        margin-left: 5px;
    }
}
```

#### 使用float


```less
.dualCol {
    position: relative;
    &::after {
        content: "."
        display: block;
        width: 0;
        height: 0;
        clear: both;
    }

    .left {
        width: 200px;
        float: left;
    }
    .right {
        margin-left: 205px; // 5px space
    }
}

```

**Comment by xvno** [comment]
## 三栏布局

分为左中右三部分, 左右宽度固定, 中间自适应

```html
<div class="clear">
    <div class="left"></div>
    <div class="mid"></div>
    <div class="right"></div>
  </div>
```

### flex 布局

```less
#tri-col-flex {
    display: flex;
    .left {
        flex: 0 0 200px;
    }
    .right{
        flex: 0 0 300px;
    }
    .mid {
        flex: auto;
        margin: 0 5px;
    }
}
```

### float 布局

```less
#tri-col-float {
    background-color: #FFFBE6;
    position: relative;
    .left {
        float: left;
        width: 200px;
    }
    .right{
        float: right;
        width: 300px;
    }
    .mid{
        position: absolute;
        top: 0;
        right: 305px;
        bottom: 0;
        left: 205px;
    }
}
```

**Comment by xvno** [comment]
## 水平/居中对齐

```html
<div class="centered">
        <div></div>
</div>
```

```less
.centered {
    background-color: #FEFBE3;
    height: 300px;
    > div {
        width: 200px;
        height: 200px;
        background-color: #2EE79D;
    }
}
```

### flex 布局

```less
.flexed {
    display:flex;
    justify-content:center;
    align-items: center;
}
```

### position 布局

```less
.positioned {
    position: relative;
    & > div {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
}
```
