### ISSUE TITLE
样式: CSS: filter

### ISSUE THREAD

**Issue by xvno** [xvno/blog#86]
## Refs

- [MDN: CSS filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)

**Comment by xvno** [comment]
## Filter functions

1. blur(radius)
2. brightness(P%): P [0, 100, +]
3. contrast(P%): P [0, 100, +]
4. drop-shadow(offsetX, offsetY, blurRadius, color)
5. grayscale(p%): p [0, 100)
6. hue-rotate(Ndeg): N [0, 360]
7. invert(p%): p [0, 100]
8. opacity(P%): P [0, 50], 0 for completely transparent
9. saturate(P%): P [0, 100, +], 0 for completely un-saturated
10. sapia(p%): p [0, 100], 100 for completely sepia

## How

```css
.class {
  // filter: fn(args)[ fn2(args2)...];
  filter: blur(10);
} 
.blured {
  filter: blur(10);
}

.combined {
  filter: blur(10) drop-shadow(5px, 5px, 10px, red);
}

.grayscaled {
  filter: grayscale(100%);
}

```
